name: Node

on:
  push:
    branches: [ main ]
    paths:
    - 'nodejs/**'
    - 'test-resources/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'nodejs/**'
    - 'test-resources/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
    - run: cd nodejs && yarn --frozen-lockfile && yarn test
