name: Node

on:
  push:
    # TODO: restore me!
    # branches: [ main ]
    branches:
      - '**'
    tags:
      - "nodejs/v**"
    paths:
    - 'nodejs/**'
    - 'test-resources/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'nodejs/**'
    - 'test-resources/**'

jobs:
  # TODO: restore me!
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@v2
  #     with:
  #       node-version: 'lts/*'
  #   - run: cd nodejs && yarn --frozen-lockfile && yarn test
  
  publish:
    runs-on: ubuntu-latest
    #  TODO: restore me!
    # if: github.ref == 'refs/heads/main'  # Runs only on commits on main branch
    # TODO: restore me!
    # needs: test
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - name: Get version from tag
      uses: actions-ecosystem/action-regex-match@v2
      id: regex-match
      with:
        text: ${{ github.ref_name }}
        regex: 'nodejs\/v(.*)'
    - name: Publish to npm
      run: |
        cd nodejs
        yarn --frozen-lockfile
        npm set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
        npm version ${{ steps.regex-match.outputs.group1 }}
        npm publish
