name: Node

on:
  push:
    # TODO: restore me!
    # branches: [ main ]
    branches:
      - '**'
    paths:
    - 'nodejs/**'
    - 'test-resources/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'nodejs/**'
    - 'test-resources/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - run: cd nodejs && yarn --frozen-lockfile && yarn test
  
  publish:
    runs-on: ubuntu-latest
    #  TODO: restore me!
    # if: github.ref == 'refs/heads/main'  # Runs only on commits on main branch
    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: Publish to NPM registry
      run: |
        cd nodejs
        npm set //registry.npmjs.org/:_authToken=${{ secrets.NUGET_API_KEY }}
        # TODO: get version from tag
        npm version 0.1.5
        npm publish
